apps/usuario/urls.py
from django.urls import path

from apps.usuario.views import Login, RegisterUser, index, ShowUser, DeleteUser, UpdateUser, Logout, Reset, ResetDone, \
    ResetConfirm, ResetComplete

app_name = 'usuario'

urlpatterns = [
    path('', index, name='index'),
    path('list', ShowUser.as_view(), name='list'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('<int:pk>/edit_user', UpdateUser.as_view(), name='edit_user'),
    path('<int:pk>/delete_user', DeleteUser.as_view(), name='delete_user'),

    path('reset/password/', Reset.as_view(), name='password_reset'),
    path('reset/password/done/', ResetDone.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', ResetConfirm.as_view(), name='password_reset_confirm'),
    path('reset/complete/', ResetComplete.as_view(), name='password_reset_complete'),
]

torneoVG/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.url')),
    path('concursante/', include('apps.concursante.urls')),
    path('carreras/', include('apps.carrera.urls')),
    path('escuelas/', include('apps.escuela.urls')),
    path('personajes/', include('apps.personaje.urls')),
    path('usuario/', include('apps.usuario.urls')),
]

apps/usuario/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    username = models.CharField(max_length=100, unique=True)
    first_name = models.CharField(max_length=60)
    last_name = models.CharField(max_length=60)
    second_last_name = models.CharField(max_length=60)
    password = models.CharField(max_length=150)
    email = models.CharField(max_length=100)

apps/usuario/forms.py
from django.contrib.auth.forms import AuthenticationForm, UsernameField, UserCreationForm, PasswordResetForm, SetPasswordForm
from django.contrib.auth import password_validation
from apps.usuario.models import User
from django import forms
from apps.usuario.backends import CustomBackendUser as Auth


class ResetForm(PasswordResetForm):
    email = forms.EmailField(max_length=254, widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'placeholder': 'Correo electrónico'
    }))


class ResetConfirmForm(SetPasswordForm):
    new_password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Nueva contraseña'
        }),
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
    )
    new_password2 = forms.CharField(
        strip=False,
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Confirmar contraseña'
        }),
    )


class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={
        'autofocus': True,
        'class': 'form_control',
        'placehorder': 'Nombre de usuario'
    }))
    password = forms.CharField(
        strip=False,
        widget=forms.PasswordInput(attrs={
            'class':'form_control',
            'placehorder':'Contraseña'
        }),
    )
    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username is not None and password:
            self.user_cache = Auth.authenticate(username=username, password=password)
            if self.user_cache is None:
                raise self.get_invalid_login_error()
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data


class AddUser(UserCreationForm):

    class Meta:
        model = User

        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'second_last_name',
            'is_staff',

        ]

        widgets = {

            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'second_last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'is_staff': forms.CheckboxInput(attrs={'class': 'form-control'}),
        }


class EditUser(forms.ModelForm):

    class Meta:
        model = User

        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'second_last_name',
            'is_staff',
            'is_superuser',

        ]

        widgets = {

            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'second_last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'is_staff': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'is_superuser': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

apps/usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from apps.usuarios.models import User

class AddUser(UserCreationForm):

    class Meta:
        model = User

        fields = [
            'password',
            'username',
            'first_name',
            'last_name',
            'email',
        ]

        widgets = {
            'password': forms.PasswordInput(attrs={'class': 'form-control'}),
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
        }

apps/usuario/views.py
from django.contrib.auth import login, logout
from apps.usuario.models import User
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from sweetify.views import SweetifySuccessMixin
from sweetify import *

from apps.usuario.forms import LoginForm, AddUser, EditUser, ResetForm, ResetConfirmForm


def index(request):
    return render(request, 'usuario/index.html')


class Login(LoginView):
    form_class = LoginForm
    template_name = 'usuario/login.html'
    success_url = reverse_lazy('home:index')

    def form_valid(self, form):
        login(self.request, form.get_user())
        info(self.request, 'Bienvenido(a) '+str(self.request.user.username)+'!', toast=True, position='top', timer=2500)
        return HttpResponseRedirect(self.success_url)


class Logout(LogoutView):
    success_url = reverse_lazy('usuario:login')

    def dispatch(self, request, *args, **kwargs):
        logout(request)
        success_url = self.success_url
        if success_url:
            # Redirect to this page until the session has been cleared.
            return HttpResponseRedirect(success_url)
        return super().dispatch(request, *args, **kwargs)


def index(request):
    usuario = User.objects.all()
    return render(request, 'usuario/index.html', {'object_list': usuario})


class ShowUser(ListView):
    model = User
    template_name = 'usuario/table.html'



class RegisterUser(CreateView):
    model = User
    form_class = AddUser
    template_name = 'usuario/add_usuario.html'
    success_url = reverse_lazy('usuario:index')


class UpdateUser(UpdateView):
    model = User
    form_class = EditUser
    template_name = 'usuario/edit_user.html'
    success_url = reverse_lazy('usuario:index')
    context_object_name = 'usuario'


class DeleteUser(DeleteView):
    model = User
    template_name = 'usuario/delete_user.html'
    success_url = reverse_lazy('usuario:index')


class Table(ListView):
    model = User
    template_name = 'usuario/table.html'
    paginate_by = 2


class Reset(SweetifySuccessMixin, PasswordResetView):
    template_name = "restaurar_pass/password_reset_form.html"
    email_template_name = "restaurar_pass/password_reset_email.html"
    form_class = ResetForm
    sweetify_options = {'toast': True, 'position': 'top', 'timer': 2500}
    success_message = 'Correo enviado correctamente.!'
    success_url = reverse_lazy('usuario:password_reset_done')


class ResetDone(PasswordResetDoneView):
    template_name = "restaurar_pass/password_reset_done.html"


class ResetConfirm(SweetifySuccessMixin, PasswordResetConfirmView):
    template_name = "restaurar_pass/password_reset_confirm.html"
    form_class = ResetConfirmForm
    sweetify_options = {'toast': True, 'position': 'top', 'timer': 2500}
    success_message = 'Contraseña restablecida correctamente!'
    success_url = reverse_lazy('usuario:password_reset_complete')


class ResetComplete(PasswordResetCompleteView):
    template_name = "restaurar_pass/password_reset_complete.html"

templates/usuario/add_usuario.html
{% extends 'base/main.html' %}
{% load staticfiles %}
{% block title %}Smash {% endblock %}
{% block type %}{% endblock %}
{% block content %}
    <div class="page-header header-filter clear-filter" data-parallax="true" style=" background-image: url('{% static '/assets/img/black.jpg'%}'); height: 40vh">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    {% if object.id %}
                        <h2 class="title">Editar usuario {{ object.username }}</h2>
                    {% else %}
                        <h2 class="title">Registrar nuevo usuario</h2>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="main main-raised">
        <div class="container">
            <div class="section text-center">
                <div class="col-md-8 ml-auto mr-auto">
                    <form id="form" class="form-horizontal" name="form" method="post">
                        {% csrf_token %}
                        <div class="row text-left">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <label for="nickname">Nombre de usuario</label>
                                    {{ form.username }}
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="nombre">Nombre(s)</label>
                                    {{ form.first_name }}
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="apaterno">Apellido Paterno</label>
                                    {{ form.last_name }}
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="apaterno">Apellido Materno</label>
                                    {{ form.second_last_name }}
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="email">Email / Correo electronico</label>
                                    {{ form.email }}
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="password">Contraseña</label>
                                    <input type="password" name="password1" class="form-control" id="password1" value="">
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="password">Confirmar contraseña</label>
                                    <input type="password" name="password2" class="form-control" id="password2" value="">
                                </div>
                            </div>
                        </div>

                        <div>
                            <input type="submit" class="btn btn-primary btn-round" value="Guardar">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/usuario/delete_user.html
{% extends 'base/main.html' %}
{% load staticfiles %}
{% block title %}Smash {% endblock %}
{% block type %}{% endblock %}

{% block content %}
    <div class="page-header header-filter clear-filter" data-parallax="true" style=" background-image: url('{% static '/assets/img/black.jpg'%}'); height: 40vh">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2 class="title">Eliminar usuario</h2>
                </div>
            </div>
        </div>
    </div>
    <div class="main main-raised">
        <div class="container">
            <div class="section text-center">
                <div class="col-md-8 ml-auto mr-auto">
                    <form id="form" class="form-horizontal" name="form" method="post">
                        {% csrf_token %}
                        <div class="row text-center">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <h3>¿Seguro que desea eliminar al usuario {{ object.username }} ? </h3>
                                    <button type="submit" rel="tooltip" class="btn btn-danger btn-primary btn-round" data-toggle="tooltip" data-placement="top" title="Eliminar">Si, estoy seguro</button>
                                </div>
                            </div>
                        </div>
                        <a href="{% url 'usuario:index' %}">
                            <button type="button" class="btn btn-primary btn-round" data-toggle="tooltip" data-placement="top" >Cancelar</button>
                        </a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/usuario/edit_user.html
{% extends 'base/main.html' %}
{% load staticfiles %}
{% block title %}Smash {% endblock %}
{% block type %}{% endblock %}
{% block content %}
    <div class="page-header header-filter clear-filter" data-parallax="true" style=" background-image: url('{% static '/assets/img/black.jpg'%}'); height: 40vh">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                        <h2 class="title">Editar usuario {{ object.username }}</h2>
                </div>
            </div>
        </div>
    </div>
    <div class="main main-raised">
        <div class="container">
            <div class="section text-center">
                <div class="col-md-8 ml-auto mr-auto">
                    <form id="form" class="form-horizontal" name="form" method="post">
                        {% csrf_token %}
                        <div class="row text-left">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <label for="nickname">Nombre de usuario</label>
                                    {{ form.username }}
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="nombre">Nombre(s)</label>
                                    {{ form.first_name }}
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="apaterno">Apellido Paterno</label>
                                    {{ form.last_name }}
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="apaterno">Apellido Materno</label>
                                    {{ form.second_last_name }}
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="email">Email / Correo electronico</label>
                                    {{ form.email }}
                                </div>
                            </div>
                            <br><br><br>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <div class="form-check">
                                        <label class="form-check-label">
                                            {{ form.is_staff }}
                                            Administrador
                                            <span class="form-check-sign">
                                                <span class="check"></span>
                                            </span>
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <div class="form-check">
                                        <label class="form-check-label">
                                            {{ form.is_superuser }}
                                            Super Administrador
                                            <span class="form-check-sign">
                                                <span class="check"></span>
                                            </span>
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <br>
                        <div>
                            <input type="submit" class="btn btn-primary btn-round" value="Guardar">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/usuario/index.html
{% extends 'base/main.html' %}
{% load staticfiles %}
{% block title %}Smash {% endblock %}
{% block type %}{% endblock %}
{% block content %}
    <!-- Titulo o encabezado -->
    <div class="page-header header-small clear-filter" data-parallax="true" style="background-image: url('{% static '/assets/img/black.jpg' %}'); height: 20vh ">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h2 class="title">Administradores</h2>
                </div>
            </div>
        </div>
    </div>
    <!-- divs necesarios para el contenido -->
    <div class="main main-raised">
        <div class="container">
            <div class="section text-center">
                {% include 'usuario/table.html' %}

                <a href="{% url 'usuario:register' %}">
                    <button type="button" class="btn btn-primary btn-round" data-toggle="tooltip" data-placement="top" title="Añadir un administrador"><i class="material-icons">add</i>Añadir</button>
                </a>

            </div>
        </div>
    </div>

{% endblock %}

templates/usuario/login.html
{% extends 'base/main.html' %}
{% load staticfiles %}
{% block title %}Smash {% endblock %}
{% block content %}
    <div class="page-header header-filter clear-filter" data-parallax="true" style="background-image: url('{% static '/assets/img/black.jpg' %}');">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-6 ml-auto mr-auto">
                    <div class="card card-login" style="">
                        <form class="form" method="post" action="">
                            {% csrf_token %}
                            <div class="card-header card-header-primary text-center">
                                <h4 class="card-title">Inicio de Sesión</h4>
                                <!--<div class="social-line">
                                    <a href="#pablo" class="btn btn-just-icon btn-link">
                                        <i class="fa fa-facebook-square"></i>
                                    </a>
                                    <a href="#pablo" class="btn btn-just-icon btn-link">
                                        <i class="fa fa-twitter"></i>
                                    </a>
                                    <a href="#pablo" class="btn btn-just-icon btn-link">
                                        <i class="fa fa-google-plus"></i>
                                    </a>
                                </div>-->
                            </div>
                            <div class="card-body">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">
                                            <i class="material-icons">person</i>
                                        </span>
                                    </div>
                                    <input type="text" class="form-control" placeholder="Nombre de usuario..." name="username">
                                </div>
                                <!--<div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">
                                            <i class="material-icons">mail</i>
                                        </span>
                                    </div>
                                    <input type="email" class="form-control" placeholder="Email...">
                                </div>-->
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">
                                            <i class="material-icons">lock_outline</i>
                                        </span>
                                    </div>
                                    <input type="password" class="form-control" placeholder="Contraseña..." name="password">
                                </div>
                            </div>
                            <div class="form-check">
                                <div class="text-center">
                                    <input type="submit" value="Iniciar Sesión" class="btn btn-primary btn-round">
                                    <!--<label data-toggle="tooltip" data-placement="right"
                                           title="Elegir Recuérdame reduce el número de veces que se te pedirá que inicies sesión en este dispositivo. Para mantener tu cuenta segura, usa esta opción sólo en tus dispositivos personales." class="form-check-label">
                                        <input class="form-check-input" type="checkbox" >
                                        <span class="form-check-sign">
                                            <span class="check"></span>
                                        </span>Recuérdame
                                    </label>-->
                                </div>
                            </div>
                            <div class="footer text-center">

                                <a href="{% url 'usuario:password_reset' %}" class="btn btn-primary btn-link btn-wd btn-lg" style="color: #e13103">¿Olvidaste tu contraseña?</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/usuario/table.html
<table class="table">
    <thead>
    <tr>
        <th class="text-center">Nombre de usuario</th>
        <th class="text-center">Nombre(s)</th>
        <th class="text-center">Correo</th>
        <th class="text-center">Acciones</th>
    </tr>
    </thead>
    <tbody class="text-center">
    {% if object_list %}
        {% for usuario in object_list %}
            <tr>
                <td >{{ usuario.username }}</td>
                <td >{{ usuario.first_name }} {{ usuario.last_name }} {{ usuario.second_last_name }}</td>
                <td >{{ usuario.email }}</td>
                <td  class="text-center">
                    <form action="" method="POST">
                        {% csrf_token %}
                        <a href="{% url 'usuario:edit_user' usuario.id %}">
                            <button type="button" rel="tooltip" class="btn btn-success btn-fab btn-round" data-toggle="tooltip" data-placement="top" title="Editar"><i class="material-icons">edit</i></button>
                        </a>
                        <a href="{% url 'usuario:delete_user' usuario.id %} ">
                            <button type="button" rel="tooltip" class="btn btn-danger btn-fab btn-round" data-toggle="tooltip" data-placement="top" title="Eliminar"><i class="material-icons">delete_forever</i></button>
                        </a>
                    </form>
                </td>
            </tr>
        {% endfor %}
    {% else %}
        <tr>
            <td colspan="5">
                No se han obtenido resultados de la búsqueda
            </td>
        </tr>
    {% endif %}

    </tbody>
    <tfoot>
    <tr>
        <td class="text-center" colspan="5">

        </td>
    </tr>
    </tfoot>
</table>
    <ul class="pagination justify-content-center">
        <li class="page-item">
            {% if page_obj.has_previous %}
                <a class="btn btn-dark btn-fab btn-round" href="?page={{ page_obj.previous_page_number }}"><i class="material-icons">arrow_back</i></a>
            {% endif %}
        </li>
        <li class="page-item">
            {% if page_obj.has_next %}
                <a class="btn btn-dark btn-fab btn-round" href="?page={{ page_obj.next_page_number }}"><i class="material-icons">arrow_forward</i></a>
            {% endif %}
        </li>
    </ul>