apps/carrera/urls.py
from django.urls import path
from apps.carrera.views import index, ShowCarrera, CreateCarrera, UpdateCarrera, DeleteCarrera

app_name = 'carrera'

urlpatterns = [
    path('', ShowCarrera.as_view(), name='index'),
    path('add_carrera', CreateCarrera.as_view(), name='add_carrera'),
    path('<int:pk>/edit_carrera', UpdateCarrera.as_view(), name='edit_carrera'),
    path('<int:pk>/delete_carrera', DeleteCarrera.as_view(), name='delete_carrera'),
]

apps/escuela/urls.py
from django.urls import path
from apps.escuela.views import ShowEscuela, CreateEscuela, UpdateEscuela, DeleteEscuela

app_name = 'escuela'

urlpatterns = [
    path('', ShowEscuela.as_view(), name='index'),
    path('add_escuela', CreateEscuela.as_view(), name='add_escuela'),
    path('<int:pk>/edit_escuela', UpdateEscuela.as_view(), name='edit_escuela'),
    path('<int:pk>/delete_escuela', DeleteEscuela.as_view(), name='delete_escuela'),
]

apps/personaje/urls.py
from django.urls import path
from apps.personaje.views import ShowPersonaje, DeletePersonaje, upload_file, UpdatePersonaje

app_name = 'personaje'

urlpatterns = [
    path('', ShowPersonaje.as_view(), name='index'),
    #path('add_personaje', CreatePersonaje.as_view(), name='add_personaje'),
    path('<int:pk>/edit_personaje', UpdatePersonaje.as_view(), name='edit_personaje'),
    path('<int:pk>/delete_personaje', DeletePersonaje.as_view(), name='delete_personaje'),
    path('add_personaje', upload_file, name="add_personaje"),
]

apps/usuario/urls.py
from django.urls import path

from apps.usuario.views import Login, RegisterUser, index, ShowUser, DeleteUser, UpdateUser, Logout, Reset, ResetDone, \
    ResetConfirm, ResetComplete

app_name = 'usuario'

urlpatterns = [
    path('', index, name='index'),
    path('list', ShowUser.as_view(), name='list'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('<int:pk>/edit_user', UpdateUser.as_view(), name='edit_user'),
    path('<int:pk>/delete_user', DeleteUser.as_view(), name='delete_user'),

    path('reset/password/', Reset.as_view(), name='password_reset'),
    path('reset/password/done/', ResetDone.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', ResetConfirm.as_view(), name='password_reset_confirm'),
    path('reset/complete/', ResetComplete.as_view(), name='password_reset_complete'),
]

torneoVG/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.url')),
    path('concursante/', include('apps.concursante.urls')),
    path('carreras/', include('apps.carrera.urls')),
    path('escuelas/', include('apps.escuela.urls')),
    path('personajes/', include('apps.personaje.urls')),
    path('usuario/', include('apps.usuario.urls')),
]

templates/base/main.html
{% load staticfiles %}
<html lang="es">
<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/apple-icon.png' %}">
    <link rel="icon" type="image/png" href="{% static 'assets/img/SmashLogo.png' %}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

<!-- sirve para mandar los token en el header -->

    <title>{% block title %} {% endblock %}</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
<!--     Fonts and icons     -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
<!-- CSS Files -->
    <link href="{% static 'assets/css/material-kit.css' %}?v=2.0.3" rel="stylesheet" />
    <!--<script src="{% static 'assets/js/sweetalert2.all.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/js/sweetalert2.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/js/message_methods.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/js/general_methods.js' %}" type="text/javascript"></script>
    <script src="https://unpkg.com/sweetalert2@7.18.0/dist/sweetalert2.all.js"></script>-->
</head>
<body class="{% block type %} {% endblock %}">
<nav class="navbar navbar-transparent navbar-color-on-scroll fixed-top navbar-expand-lg bg-success" color-on-scroll="100" id="sectionsNav">
    <div class="container">
        <div class="navbar-translate">
            <a class="navbar-brand" href="/"> Inicio </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                <span class="navbar-toggler-icon"></span>
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse">

            <ul class="nav navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    {% if user.is_staff or user.is_superuser %}
                        <li class="dropdown nav-item">
                            <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                                <i class="material-icons">book</i> Carrera
                            </a>
                            <div class="dropdown-menu dropdown-with-icons"> </a>
                                <a href="{% url 'carrera:index' %}" class="dropdown-item">
                                    <i class="material-icons">list</i> Ver carreras
                                </a>
                                <a href="{% url 'carrera:add_carrera' %}" class="dropdown-item">
                                    <i class="material-icons">add</i> Agregar carrera
                                </a>
                            </div>
                        </li>

                        <li class="dropdown nav-item">
                            <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                                <i class="material-icons">school</i> Institución
                            </a>
                            <div class="dropdown-menu dropdown-with-icons">
                                <a href="{% url 'escuela:index' %}" class="dropdown-item">
                                    <i class="material-icons">list</i> Ver instituciones
                                </a>
                                <a href="{% url 'escuela:add_escuela' %}" class="dropdown-item">
                                    <i class="material-icons">add</i> Agregar institución
                                </a>
                            </div>
                        </li>
                    {% endif %}
                        <li class="dropdown nav-item">
                            <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                                <i class="material-icons">games</i> Personajes
                            </a>
                            <div class="dropdown-menu dropdown-with-icons">
                                <a href="{% url 'personaje:index' %}" class="dropdown-item">
                                    <i class="material-icons">list</i> Ver personajes
                                </a>
                                {% if user.is_staff or user.is_superuser %}
                                    <a href="{% url 'personaje:index' %}" class="dropdown-item">
                                        <i class="material-icons">add</i> Añadir personajes
                                    </a>
                                {% endif %}
                            </div>
                        </li>

                        <li class="dropdown nav-item">
                            <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                                <i class="material-icons">supervisor_account</i> Administración
                            </a>
                            <div class="dropdown-menu dropdown-with-icons">
                                {% if user.is_staff or user.is_superuser %}
                                    <h6 class="dropdown-header">Administradores</h6>
                                    <a href="{% url 'usuario:index' %}" class="dropdown-item">
                                        <i class="material-icons">list</i>Administradores
                                    </a>
                                    <div class="dropdown-divider"></div>
                                {% endif %}
                                <a href="/concursante" class="dropdown-item">
                                    <i class="material-icons">people</i> Concursantes
                                </a>
                            </div>
                        </li>
                        <li class="dropdown nav-item">
                            <a href="#" class="profile-photo dropdown-toggle nav-link" data-toggle="dropdown">
                                <div class="profile-photo-small">
                                    <img src="{% static 'assets/img/faces/camp.jpg'%}" alt="Circle Image" class="rounded-circle img-fluid">
                                </div>
                            </a>
                            <div class="dropdown-menu dropdown-with-icons">
                                <a href="#" class="dropdown-item">
                                    <i class="material-icons">account_circle</i>{{ user.username }}
                                </a>
                                <a class="dropdown-item" href="{% url 'usuario:logout' %}">
                                    <i class="material-icons">exit_to_app</i>Cerrar sesión
                                </a>
                                <form id="logout-form" action="" method="POST" style="display: none;">

                                </form>
                            </div>
                        </li>

                {% else %}
                    <li class="dropdown nav-item">
                        <a href="{% url 'usuario:login' %}" class=" nav-link"> <i class="material-icons">input</i> Iniciar sesión </a>
                    </li>
                    <li class="dropdown nav-item">
                        <a href="{% url 'concursante:add_concursante' %}" class="nav-link"> <i class="material-icons">person_add</i> Registrarse </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% block content %}

{% endblock %}
<!--  End Modal -->
<footer class="footer" data-background-color="black">
    <div class="container">
        <nav class="float-left">
            <ul>
                <a class="sharing-area" href="https://www.facebook.com/cuvalles" target="_blank">
                    <button class="btn btn-fab btn-round btn-facebook">
                        <i class="fa fa-facebook"> </i>
                    </button>
                </a>
                <a class="sharing-area" href="https://twitter.com/MnDMzTR" target="_blank">
                    <button class="btn btn-fab btn-round btn-twitter">
                        <i class="fa fa-twitter"> </i>
                    </button>
                </a>
                <!--<li>
                <a href="https://www.creative-tim.com">
                Creative Tim
                </a>
                </li>
                <li>
                <a href="https://presentation.creative-tim.com">
                About Us
                </a>
                </li>
                <li>
                <a href="https://blog.creative-tim.com">
                Blog
                </a>
                </li>
                <li>
                <a href="https://www.creative-tim.com/license">
                Licenses
                </a>
                </li>-->
            </ul>
        </nav>
        <div class="copyright float-right"> &copy;
            <script> document.write(new Date().getFullYear())
            </script> <a href="http://www.valles.udg.mx/" target="_blank">CUValles</a>
        </div>
    </div>
</footer>
<!--   Core JS Files   -->
<script src="{% static 'assets/js/core/jquery.min.js'%}" type="text/javascript"></script>
<script src="{% static 'assets/js/core/popper.min.js'%}" type="text/javascript"></script>
<script src="{% static 'assets/js/core/bootstrap-material-design.min.js'%}" type="text/javascript"></script>
<script src="{% static 'assets/js/plugins/moment.min.js' %}"></script>
<!--	Plugin for the Datepicker, full documentation here: https://github.com/Eonasdan/bootstrap-datetimepicker -->
<script src="{% static 'assets/js/plugins/bootstrap-datetimepicker.js' %}" type="text/javascript"></script>
<!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
<script src="{% static 'assets/js/plugins/nouislider.min.js'%}" type="text/javascript"></script>
<!-- Control Center for Now Ui Kit: parallax effects, scripts for the example pages etc -->
<script src="{% static 'assets/js/material-kit.js'%}?v=2.0.3" type="text/javascript"></script>
<script src="https://unpkg.com/sweetalert2@7.22.2/dist/sweetalert2.all.js"></script>
<script src="{% static 'assets/js/mensajes.js' %}" type="text/javascript"></script>
{% load sweetify %} {% sweetify %}

</body>
</html>