apps/personaje/urls.py
from django.urls import path
from apps.personaje.views import ShowPersonaje, DeletePersonaje, upload_file, UpdatePersonaje

app_name = 'personaje'

urlpatterns = [
    path('', ShowPersonaje.as_view(), name='index'),
    #path('add_personaje', CreatePersonaje.as_view(), name='add_personaje'),
    path('<int:pk>/edit_personaje', UpdatePersonaje.as_view(), name='edit_personaje'),
    path('<int:pk>/delete_personaje', DeletePersonaje.as_view(), name='delete_personaje'),
    path('add_personaje', upload_file, name="add_personaje"),
]

torneoVG/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.url')),
    path('concursante/', include('apps.concursante.urls')),
    path('carreras/', include('apps.carrera.urls')),
    path('escuelas/', include('apps.escuela.urls')),
    path('personajes/', include('apps.personaje.urls')),
    path('usuario/', include('apps.usuario.urls')),
]

apps/personaje/models.py
from django.db import models

# Create your models here.
class Personaje(models.Model):
    nombre = models.CharField(max_length=100)
    imagen = models.FileField(upload_to='')

    def __str__(self):
        return '{}'.format(self.nombre)

apps/personaje/forms.py
from django import forms

from apps.personaje.models import Personaje


class AddPersonaje(forms.ModelForm):
    class Meta:
        model = Personaje

        fields = [
            'nombre',
            'imagen'
        ]

        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'imagen': forms.FileInput(attrs={'class': 'form-control'}),
        }


class UploadForm(forms.Form):
    filename = forms.CharField(max_length=100)
    docfile = forms.FileField(label='Selecciona un archivo')

apps/personaje/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DeleteView, UpdateView

from apps.personaje.forms import AddPersonaje, UploadForm
from apps.personaje.models import Personaje


def index(request):
    return render(request, 'personaje/index.html')


class ShowPersonaje(ListView):
    model = Personaje
    template_name = 'personaje/index.html'
    paginate_by = 5


#class CreatePersonaje(CreateView):
#   model = Personaje
#    form_class = AddPersonaje
#    template_name = 'personaje/add_personaje.html'
#    success_url = reverse_lazy('personaje:index')


class UpdatePersonaje(UpdateView):
    model = Personaje
    form_class = AddPersonaje
    template_name = 'personaje/add_personaje.html'
    success_url = reverse_lazy('personaje:index')


class DeletePersonaje(DeleteView):
    model = Personaje
    template_name = 'personaje/delete_personaje.html'
    success_url = reverse_lazy('personaje:index')


def upload_file(request):
    if request.method == 'POST':
        form = AddPersonaje(request.POST, request.FILES)
        if form.is_valid():
            newdoc = Personaje(nombre=request.POST['nombre'], imagen=request.FILES['imagen'])
            newdoc.save(form)
            return redirect("personaje:index")
    else:
        form = AddPersonaje()
    #tambien se puede utilizar render_to_response
    #return render_to_response('upload.html', {'form': form}, context_instance = RequestContext(request))
    return render(request, 'personaje/add_personaje.html', {'form': form})

templates/personaje/add_personaje.html
{% extends 'base/main.html' %}
{% load staticfiles %}
{% block title %}Smash {% endblock %}
{% block type %}{% endblock %}

{% block content %}
    <div class="page-header header-filter clear-filter" data-parallax="true" style=" background-image: url('{% static '/assets/img/black.jpg'%}'); height: 40vh">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2 class="title">Registrar nuevo personaje</h2>
                </div>
            </div>
        </div>
    </div>
    <div class="main main-raised">
        <div class="container">
            <div class="section text-center">
                <div class="col-md-8 ml-auto mr-auto">
                    <form id="form" class="form-horizontal" name="form" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row text-left">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="nickname">Nombre del personaje</label>
                                    {{ form.nombre }}
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div>
                                    <span class="btn btn-raised btn-round btn-default btn-file">
                                        {{ form.imagen }}</span>
                                </div>
                            </div>
                        </div>
                        <div>
                            <input type="submit" class="btn btn-primary btn-round" value="Guardar">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/personaje/delete_personaje.html
{% extends 'base/main.html' %}
{% load staticfiles %}
{% block title %}Smash {% endblock %}
{% block type %}{% endblock %}

{% block content %}
    <div class="page-header header-filter clear-filter" data-parallax="true" style=" background-image: url('{% static '/assets/img/black.jpg'%}'); height: 40vh">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2 class="title">Eliminar personaje</h2>
                </div>
            </div>
        </div>
    </div>
    <div class="main main-raised">
        <div class="container">
            <div class="section text-center">
                <div class="col-md-8 ml-auto mr-auto">
                    <form id="form" class="form-horizontal" name="form" method="post">
                        {% csrf_token %}
                        <div class="row text-center">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <h3>¿Seguro que desea eliminar al pesonaje {{ object.nombre }} ? </h3>
                                    <button type="submit" rel="tooltip" class="btn btn-danger btn-primary btn-round" data-toggle="tooltip" data-placement="top" title="Eliminar">Si, estoy seguro</button>
                                </div>
                            </div>
                        </div>
                        <a href="{% url 'personaje:index' %}">
                            <button type="button" class="btn btn-primary btn-round" data-toggle="tooltip" data-placement="top" >Cancelar</button>
                        </a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/personaje/index.html
{% extends 'base/main.html' %}
{% load staticfiles %}
{% block title %}Smash {% endblock %}
{% block type %}{% endblock %}
{% block content %}
    <!-- Titulo o encabezado -->
    <div class="page-header header-small clear-filter" data-parallax="true" style="background-image: url('{% static '/assets/img/black.jpg' %}'); height: 10vh ">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <h2 class="title">Personajes</h2>
                </div>
            </div>
        </div>
    </div>
    <!-- divs necesarios para el contenido -->
    <div class="main main-raised">
        <div class="container">
            <div class="section text-center">
                <table class="table">
                    <thead>
                    <tr>

                        <th class="text-center">Personaje</th>
                        <th></th>
                        <th class="text-center">Acciones</th>
                    </tr>
                    </thead>
                    <tbody class="text-center">
                    {% if object_list %}
                        {% for personaje in object_list %}
                            <tr>

                                <td >{{ personaje.nombre }} </td>
                                <td>{% if personaje.imagen %}
                                    <img src="../../static/assets/img/personajes/{{ personaje.imagen }}" height="50">
                                {% else %}
                                    <img src="../../static/assets/img/personajes/No.png" height="50">
                                {% endif %}</td>
                                <td class="text-center">
                                    <form action="" method="POST">
                                        {% csrf_token %}
                                        <a href="{% url 'personaje:edit_personaje' personaje.id %}">
                                            <button type="button" rel="tooltip" class="btn btn-success btn-fab btn-round" data-toggle="tooltip" data-placement="top" title="Editar"><i class="material-icons">edit</i></button>
                                        </a>
                                        <a href="{% url 'personaje:delete_personaje' personaje.id %}">
                                            <button type="button" rel="tooltip" class="btn btn-danger btn-fab btn-round" data-toggle="tooltip" data-placement="top" title="Eliminar"><i class="material-icons">delete_forever</i></button>
                                        </a>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td colspan="5">
                                No se han obtenido resultados de la búsqueda
                            </td>
                        </tr>
                    {% endif %}

                    </tbody>
                    <tfoot>
                    <tr>
                        <td class="text-center" colspan="4">

                        </td>
                    </tr>
                    </tfoot>
                </table>
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        <li class="page-item">
                            {% if page_obj.has_previous %}
                                <a class="btn btn-dark btn-default btn-round" href="?page=1">Inicio</a>
                                <a class="btn btn-dark btn-fab btn-round" href="?page={{ page_obj.previous_page_number }}"><i class="material-icons">arrow_back</i></a>
                            {% endif %}
                        </li>
                        <li class="page-item">
                            {% if page_obj.has_next %}
                                <a class="btn btn-dark btn-fab btn-round" href="?page={{ page_obj.next_page_number}}"><i class="material-icons">arrow_forward</i></a>
                                <a class="btn btn-dark btn-default btn-round" href="?page={{ page_obj.paginator.num_pages }}">Ultima</a>
                            {% endif %}
                        </li>
                    </ul>
                </nav>
                <a href=" {% url 'personaje:add_personaje' %}">
                    <button type="button" class="btn btn-primary btn-round" data-toggle="tooltip" data-placement="top" title="Añadir una carrera"><i class="material-icons">add</i>Añadir</button>
                </a>
            </div>
        </div>
    </div>

{% endblock %}