apps/carrera/urls.py
from django.urls import path
from apps.carrera.views import index, ShowCarrera, CreateCarrera, UpdateCarrera, DeleteCarrera

app_name = 'carrera'

urlpatterns = [
    path('', ShowCarrera.as_view(), name='index'),
    path('add_carrera', CreateCarrera.as_view(), name='add_carrera'),
    path('<int:pk>/edit_carrera', UpdateCarrera.as_view(), name='edit_carrera'),
    path('<int:pk>/delete_carrera', DeleteCarrera.as_view(), name='delete_carrera'),
]

torneoVG/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.url')),
    path('concursante/', include('apps.concursante.urls')),
    path('carreras/', include('apps.carrera.urls')),
    path('escuelas/', include('apps.escuela.urls')),
    path('personajes/', include('apps.personaje.urls')),
    path('usuario/', include('apps.usuario.urls')),
]

apps/carrera/models.py
from django.db import models

# Create your models here.
class Carrera(models.Model):
    nombre_carrera = models.CharField(max_length=60)

    def __str__(self):
        return '{}'.format(self.nombre_carrera)

apps/carrera/forms.py
from django import forms

from apps.carrera.models import Carrera


class AddCarrera(forms.ModelForm):
    class Meta:
        model = Carrera

        fields = [
             'nombre_carrera'
        ]

        labels = {
            'nombre_carrera': 'Nombre de la carrera'
        }

        widgets = {
            'nombre_carrera' : forms.TextInput(attrs={'class': 'form-control'}),
        }

apps/carrera/views.py
from django.core.paginator import Paginator
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from apps.carrera.forms import AddCarrera
from apps.carrera.models import Carrera
from sweetify.views import SweetifySuccessMixin


def index(request):
    return render(request, 'carrera/index.html')

class ShowCarrera(ListView):
    model = Carrera
    template_name = 'carrera/index.html'
    paginate_by = 4
    ordering = ['id']


class CreateCarrera(SweetifySuccessMixin, CreateView):
    model = Carrera
    form_class = AddCarrera
    template_name = 'carrera/add_carrera.html'
    sweetify_options = {'toast': True, 'position': 'top-left', 'timer': 3000}
    success_message = 'Carrera guardada correctamente'
    success_url = reverse_lazy('carrera:index')


class UpdateCarrera(SweetifySuccessMixin, UpdateView):
    model = Carrera
    form_class = AddCarrera
    template_name = 'carrera/add_carrera.html'
    sweetify_options = {'toast': True, 'position': 'top-left', 'timer': 3000}
    success_message = 'Carrera actualizada correctamente'
    success_url = reverse_lazy('carrera:index')


class DeleteCarrera(SweetifySuccessMixin, DeleteView):
    model = Carrera
    template_name = 'carrera/delete_carrera.html'
    sweetify_options = {'toast': True, 'position': 'top-left', 'timer': 3000}
    success_message = 'Carrera eliminada correctamente'
    success_url = reverse_lazy('carrera:index')


def get_queryset(self,npagina=1):
    consulta = Carrera.objects.all()
    paginacion = Paginator(consulta,'cantidad objetos')
    if len(paginacion.page(1)) == 0:
        return None
    else:
        return paginacion.page(npagina)

templates/carrera/add_carrera.html
{% extends 'base/main.html' %}
{% load staticfiles %}
{% block title %}Smash {% endblock %}
{% block type %}{% endblock %}

{% block content %}
    <div class="page-header header-filter clear-filter" data-parallax="true" style=" background-image: url('{% static '/assets/img/black.jpg'%}'); height: 40vh">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2 class="title">Registrar nueva carrera</h2>
                </div>
            </div>
        </div>
    </div>
    <div class="main main-raised">
        <div class="container">
            <div class="section text-center">
                <div class="col-md-8 ml-auto mr-auto">
                    <form id="form" class="form-horizontal" name="form" method="post">
                        {% csrf_token %}
                        <div class="row text-left">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <label for="nickname">Nombre de la carrera</label>
                                    {{ form.nombre_carrera }}
                                </div>
                            </div>
                        </div>
                        <div>
                            <input type="submit" class="btn btn-primary btn-round" value="Guardar">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/carrera/delete_carrera.html
{% extends 'base/main.html' %}
{% load staticfiles %}
{% block title %}Smash {% endblock %}
{% block type %}{% endblock %}

{% block content %}
    <div class="page-header header-filter clear-filter" data-parallax="true" style=" background-image: url('{% static '/assets/img/black.jpg'%}'); height: 40vh">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2 class="title">Eliminar carrera</h2>
                </div>
            </div>
        </div>
    </div>
    <div class="main main-raised">
        <div class="container">
            <div class="section text-center">
                <div class="col-md-8 ml-auto mr-auto">
                    <form id="form" class="form-horizontal" name="form" method="post">
                        {% csrf_token %}
                        <div class="row text-center">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <h3>¿Seguro que desea eliminar la carrera {{ object.nombre_carrera }} ? </h3>
                                    <button type="submit" rel="tooltip" class="btn btn-danger btn-primary btn-round" data-toggle="tooltip" data-placement="top" title="Eliminar">Si, estoy seguro</button>
                                </div>
                            </div>
                        </div>
                        <a href="{% url 'carrera:index' %}">
                            <button type="button" class="btn btn-primary btn-round" data-toggle="tooltip" data-placement="top" >Cancelar</button>
                        </a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/carrera/index.html
{% extends 'base/main.html' %}
{% load staticfiles %}
{% block title %}Smash {% endblock %}
{% block type %}{% endblock %}
{% block content %}

    <!-- Titulo o encabezado -->
    <div class="page-header header-small clear-filter" data-parallax="true" style="background-image: url('{% static '/assets/img/black.jpg' %}'); height: 10vh ">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h2 class="title">Carreras</h2>
                </div>
            </div>
        </div>
    </div>
    <!-- divs necesarios para el contenido -->
    <div class="main main-raised">
        <div class="container">
            <div class="section text-center">
                <table class="table">
                    <thead>
                    <tr>
                        <th class="text-center">#</th>
                        <th class="text-center">Nombre de la carrera</th>
                        <th class="text-center">Acciones</th>
                    </tr>
                    </thead>
                    <tbody class="text-center">
                    {% if object_list %}
                        {% for carrera in object_list %}
                            <tr>
                                <td>{{ carrera.id }}</td>
                                <td>{{ carrera.nombre_carrera }}</td>
                                <td  class="text-center">
                                    <form action="" method="POST">
                                        {% csrf_token %}
                                        <a href="{% url 'carrera:edit_carrera' carrera.id %}">
                                            <button type="button" rel="tooltip" class="btn btn-success btn-fab btn-round" data-toggle="tooltip" data-placement="top" title="Editar"><i class="material-icons">edit</i></button>
                                        </a>
                                        <button title="Eliminar" onclick="deleteElement(event, '{{ carrera.nombre_carrera }}' ,'{% url 'carrera:delete_carrera' carrera.id %}')" type="button" rel="tooltip" class="btn btn-danger btn-fab btn-round">
                                            <i class="material-icons">delete_forever</i>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td colspan="5">
                                No se han obtenido resultados de la búsqueda
                            </td>
                        </tr>
                    {% endif %}

                    </tbody>
                    <tfoot>
                    <tr>
                        <td class="text-center" colspan="3">

                        </td>
                    </tr>
                    </tfoot>
                </table>
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        <li class="page-item">
                            {% if page_obj.has_previous %}
                                <a class="btn btn-dark btn-default btn-round" href="?page=1">Inicio</a>
                                <a class="btn btn-dark btn-fab btn-round" href="?page={{ page_obj.previous_page_number }}"><i class="material-icons">arrow_back</i></a>
                            {% endif %}
                        </li>
                        <li class="page-item">
                            {% if page_obj.has_next %}
                                <a class="btn btn-dark btn-fab btn-round" href="?page={{ page_obj.next_page_number}}"><i class="material-icons">arrow_forward</i></a>
                                <a class="btn btn-dark btn-default btn-round" href="?page={{ page_obj.paginator.num_pages }}">Ultima</a>
                            {% endif %}
                        </li>
                    </ul>
                </nav>

                <a href="{% url 'carrera:add_carrera' %}">
                    <button type="button" class="btn btn-primary btn-round" data-toggle="tooltip" data-placement="top" title="Añadir una carrera"><i class="material-icons">add</i>Añadir</button>
                </a>

            </div>
        </div>
    </div>

{% endblock %}